#ifndef _BOARD_CONFIG_H_
#define _BOARD_CONFIG_H_

#include <driver/gpio.h>

#define AUDIO_INPUT_SAMPLE_RATE   24000
#define AUDIO_OUTPUT_SAMPLE_RATE  24000

// --- AUDIO DIRECTO I2S ---
#define AUDIO_I2S_SPK_GPIO_BCLK   GPIO_NUM_9
#define AUDIO_I2S_SPK_GPIO_LRCK   GPIO_NUM_11
#define AUDIO_I2S_SPK_GPIO_DOUT   GPIO_NUM_12
#define AUDIO_I2S_MIC_GPIO_SCK    GPIO_NUM_9
#define AUDIO_I2S_MIC_GPIO_WS     GPIO_NUM_11
#define AUDIO_I2S_MIC_GPIO_DIN    GPIO_NUM_10

// --- BOTÓN FÍSICO ÚNICO ---
#define BOOT_BUTTON_GPIO        GPIO_NUM_0
#define VOLUME_UP_BUTTON_GPIO   GPIO_NUM_NC
#define VOLUME_DOWN_BUTTON_GPIO GPIO_NUM_NC

// --- PANTALLA NV3023 (128x128) ---
#define DISPLAY_SDA GPIO_NUM_15
#define DISPLAY_SCL GPIO_NUM_16
#define DISPLAY_CS  GPIO_NUM_17
#define DISPLAY_DC  GPIO_NUM_18
#define DISPLAY_RES GPIO_NUM_14

#define DISPLAY_WIDTH   128
#define DISPLAY_HEIGHT  128
#define DISPLAY_SWAP_XY  false
#define DISPLAY_MIRROR_X false
#define DISPLAY_MIRROR_Y true
#define BACKLIGHT_INVERT false
#define DISPLAY_OFFSET_X  0
#define DISPLAY_OFFSET_Y  0

#define DISPLAY_BACKLIGHT_PIN GPIO_NUM_13
#define DISPLAY_BACKLIGHT_OUTPUT_INVERT false

#endif // _BOARD_CONFIG_H_
