name: Build Boards

on:
  push:
    branches:
      - main
      - ci/* # for ci test
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  prepare:
    name: Determine variants to build
    runs-on: ubuntu-latest
    container:
      image: espressif/idf:v6.0.1
    outputs:
      variants: ${{ steps.select.outputs.variants }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Test build tooling
        run: python -m unittest discover -s scripts/tests -v

      - id: list
        name: Get all variant list
        run: |
          echo "all_variants=$(python scripts/build.py --list-boards --json)" >> $GITHUB_OUTPUT

      - id: select
        name: Select variants based on changes
        shell: bash
        env:
          ALL_VARIANTS: ${{ steps.list.outputs.all_variants }}
        run: |
          EVENT_NAME="${{ github.event_name }}"

          # Solo compilar la placa nologo-xingzhi-cube-1.54tft-wifi
          if [[ "$EVENT_NAME" == "push" ]]; then
           TARGET_VARIANT=$(echo "$ALL_VARIANTS" | python -c "import sys, json; data=json.load(sys.stdin); print(json.dumps([v for v in data if 'xingzhi-cube-1.54tft-wifi' in str(v)]))")
            echo "variants=$TARGET_VARIANT" >> $GITHUB_OUTPUT
            exit 0
          fi

          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          BASE_SHA="HEAD^1"
          HEAD_SHA="HEAD^2"
          CHANGED=$(git diff --name-only "$BASE_SHA" "$HEAD_SHA")
          SELECTED=$(printf '%s\n' "$CHANGED" | python scripts/build.py --select-changed)
          echo "variants=$SELECTED" >> $GITHUB_OUTPUT

  build:
    name: Build ${{ matrix.full_name }}
    needs: prepare
    if: ${{ needs.prepare.outputs.variants != '[]' }}
    strategy:
      fail-fast: false
      matrix:
        include: ${{ fromJson(needs.prepare.outputs.variants) }}
    runs-on: ubuntu-latest
    container:
      image: espressif/idf:v6.0.1
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build current variant
        shell: bash
        run: |
          source $IDF_PATH/export.sh
          python scripts/build.py ${{ matrix.board }} --name ${{ matrix.name }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: xiaozhi_${{ matrix.full_name }}_${{ github.sha }}
          path: build/merged-binary.bin
          if-no-files-found: error
